name: docparser
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch>=2.0.0
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8
  - pillow>=9.0.0
  - numpy>=1.21.0
  - scikit-learn>=1.3.0
  - tqdm>=4.65.0
  - pip
  - pip:
    - transformers>=4.30.0
    - PyMuPDF>=1.23.0
    - pytesseract>=0.3.10
    - opencv-python>=4.8.0
    - scikit-image>=0.21.0
    - requests>=2.31.0
    - pathlib2>=2.3.7
    # Optional dependencies
    # - olmocr[gpu]
    # - easyocr 